apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apigateway
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30080